### ISSUE TITLE
[BUG] HTTPX Binary upload data unsuported

### ISSUE THREAD

**Issue by 07pepa** [kevin1024/vcrpy#656]
I am trying to migrate one library from requests to http and it seems httpx portion have some bugs

folowing casete cant be used with httpx
https://github.com/billdeitrick/pypco/blob/master/tests/cassettes/TestPublicRequestFunctions.test_upload_and_use_file.yaml

because it tries to decode the binary string (that is nonsense)

```
Error
Traceback (most recent call last):
  File "pypco\pypco\pco.py", line 251, in request_response
    response = self._do_url_managed_request(method, url, payload, upload, **params)
  File "pypco\pypco\pco.py", line 223, in _do_url_managed_request
    return self._do_ratelimit_managed_request(method, url, payload, upload, **params)
  File "pypco\pypco\pco.py", line 184, in _do_ratelimit_managed_request
    response = self._do_timeout_managed_request(method, url, payload, upload, **params)
  File "pypco\pypco\pco.py", line 145, in _do_timeout_managed_request
    return self._do_request(method, url, payload, upload, **params)
  File "pypco\pypco\pco.py", line 110, in _do_request
    response = self.session.request(
  File ".virtualenvs\pypco-EZZlDlNc\lib\site-packages\httpx\_client.py", line 815, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File ".virtualenvs\pypco-EZZlDlNc\lib\site-packages\vcr\stubs\httpx_stubs.py", line 168, in _inner_send
    return _sync_vcr_send(cassette, real_send, *args, **kwargs)
  File ".virtualenvs\pypco-EZZlDlNc\lib\site-packages\vcr\stubs\httpx_stubs.py", line 155, in _sync_vcr_send
    vcr_request, response = _shared_vcr_send(cassette, real_send, *args, **kwargs)
  File ".virtualenvs\pypco-EZZlDlNc\lib\site-packages\vcr\stubs\httpx_stubs.py", line 81, in _shared_vcr_send
    vcr_request = _make_vcr_request(real_request, **kwargs)
  File ".virtualenvs\pypco-EZZlDlNc\lib\site-packages\vcr\stubs\httpx_stubs.py", line 72, in _make_vcr_request
    body = httpx_request.read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 137: invalid start byte
```

**Comment by llybin** [comment]
Probably related: https://github.com/ktosiek/pytest-vcr/issues/46

**Comment by gotmax23** [comment]
Can we use `errors="surrogateescape"` here?

**Comment by 76tr75b** [comment]
I still get the same error if i upload a file via httpx in a test with vcrpy.
- Python 3.11.8
- vcrpy 6.0.1
- httpx 0.27.0

```
/usr/local/lib/python3.11/site-packages/statsd/client/timer.py:41: in _wrapped
    return f(*args, **kwargs)
src/common/client/example/client.py:39: in analyse
    result = self._httpx_client.post(
/usr/local/lib/python3.11/site-packages/httpx/_client.py:1145: in post
    return self.request(
/usr/local/lib/python3.11/site-packages/httpx/_client.py:827: in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/httpx.py:84: in send
    rv = real_send(self, request, **kwargs)
/usr/local/lib/python3.11/site-packages/httpx/_client.py:914: in send
    response = self._send_handling_auth(
/usr/local/lib/python3.11/site-packages/httpx/_client.py:942: in _send_handling_auth
    response = self._send_handling_redirects(
/usr/local/lib/python3.11/site-packages/httpx/_client.py:979: in _send_handling_redirects
    response = self._send_single_request(request)
/usr/local/lib/python3.11/site-packages/vcr/stubs/httpx_stubs.py:184: in _inner_send
    return _sync_vcr_send(cassette, real_send, *args, **kwargs)
/usr/local/lib/python3.11/site-packages/vcr/stubs/httpx_stubs.py:170: in _sync_vcr_send
    vcr_request, response = _shared_vcr_send(cassette, real_send, *args, **kwargs)
/usr/local/lib/python3.11/site-packages/vcr/stubs/httpx_stubs.py:117: in _shared_vcr_send
    vcr_request = _make_vcr_request(real_request, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

httpx_request = <Request('POST', 'http://example.com/upload')>, kwargs = {}

    def _make_vcr_request(httpx_request, **kwargs):
>       body = httpx_request.read().decode("utf-8")
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 161: invalid start byte
```

**Comment by 76tr75b** [comment]
Ok, my issue is fixed by [this](https://github.com/kevin1024/vcrpy/pull/820) PR.

**Comment by simonw** [comment]
This isssue should not be closed - PR #820 was not accepted, so the problem still occurs - it's not possible to use `httpx` mode with `multipart/form` data requests containing binary files.

**Comment by kevin1024** [comment]
Thanks @simonw. I’ll reopen.

Love your blog by the way!  Thanks for using VCR.

**Comment by finswimmer** [comment]
Hey,

I ran into this issue today as well. The monkey-patch fix provided by @simonw works for me to create the cassette. But on replay I receive a `JSONDecodeError`

```
../../../.venv/lib/python3.13/site-packages/httpx/_client.py:1896: in put
    return await self.request(
../../../.venv/lib/python3.13/site-packages/httpx/_client.py:1540: in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
../../../.venv/lib/python3.13/site-packages/httpx/_client.py:1629: in send
    response = await self._send_handling_auth(
../../../.venv/lib/python3.13/site-packages/httpx/_client.py:1657: in _send_handling_auth
    response = await self._send_handling_redirects(
../../../.venv/lib/python3.13/site-packages/httpx/_client.py:1694: in _send_handling_redirects
    response = await self._send_single_request(request)
../../../.venv/lib/python3.13/site-packages/vcr/stubs/httpx_stubs.py:150: in _async_vcr_send
    vcr_request, response = _shared_vcr_send(cassette, real_send, *args, **kwargs)
../../../.venv/lib/python3.13/site-packages/vcr/stubs/httpx_stubs.py:119: in _shared_vcr_send
    if cassette.can_play_response_for(vcr_request):
../../../.venv/lib/python3.13/site-packages/vcr/cassette.py:250: in can_play_response_for
    return request and request in self and self.record_mode != RecordMode.ALL and self.rewound
../../../.venv/lib/python3.13/site-packages/vcr/cassette.py:347: in __contains__
    for index, _ in self._responses(request):
../../../.venv/lib/python3.13/site-packages/vcr/cassette.py:245: in _responses
    if requests_match(request, stored_request, self._match_on):
../../../.venv/lib/python3.13/site-packages/vcr/matchers.py:165: in requests_match
    successes, failures = get_matchers_results(r1, r2, matchers)
../../../.venv/lib/python3.13/site-packages/vcr/matchers.py:197: in get_matchers_results
    match, assertion_message = _evaluate_matcher(m, r1, r2)
../../../.venv/lib/python3.13/site-packages/vcr/matchers.py:180: in _evaluate_matcher
    match = matcher_function(*args)
../../../.venv/lib/python3.13/site-packages/vcr/matchers.py:62: in body
    b1 = transform(b1)
../../../.venv/lib/python3.13/site-packages/vcr/matchers.py:142: in _transform_json
    return json.loads(body)
/home/finswimmer/.pyenv/versions/3.13.0/lib/python3.13/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
/home/finswimmer/.pyenv/versions/3.13.0/lib/python3.13/json/decoder.py:344: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7684a2e08d70>
s = '%PDF-1.7\n\n4 0 obj\n(Identity)\nendobj\n5 0 obj\n(Adobe)\nendobj\n8 0 obj\n<<\n/Filter /FlateDecode\n/Length 37553\n...38458 00000 n\r\n0000039676 00000 n\r\ntrailer\n<<\n/Info 14 0 R\n/Root 1 0 R\n/Size 15\n>>\nstartxref\n39881\n%%EOF\n'
idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.
    
        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.
    
        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/home/finswimmer/.pyenv/versions/3.13.0/lib/python3.13/json/decoder.py:362: JSONDecodeError
```

**Comment by kevin1024** [comment]
v8.0.0 completely rewrote httpx support (PR #943) to patch httpcore instead of httpx. The new implementation keeps request bodies as bytes without UTF-8 decoding:

```python
# New code in httpcore_stubs.py
body = b"".join(await _convert_byte_stream(real_request.stream))
return VcrRequest(real_request.method.decode("ascii"), uri, body, headers)
```

This should fix the binary upload issue. Could you please test with v8.0.0 and confirm?

**Comment by 07pepa** [comment]
@kevin1024 i tested original issue... and it is no longer issue ...

@simonw  any suggestions?

**Comment by kevin1024** [comment]
This should be resolved in the newest release (v8.2.0). The httpx support was rewritten to patch httpx's transports and capture the request body as raw bytes, so binary/multipart upload data is no longer decoded as UTF-8. Verified with binary-content and multipart binary-file-upload repros that record and replay cleanly. Please re-open if you still hit this on 8.2.0. Thanks!
